os:
  - linux
  - osx

# in theory travis should detect what to install,
# but we use meson, which is not supported by travis yet and we need custom commands
compiler:
  - gcc

language: c

env:
  global:
    DATE=$(date +%Y%m%d)
    TIME=$(date +%H%M%S)

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: 
        TARGET=linux-amd64
        EXTENSION=
    - os: linux
      env:
        TARGET=linux-armhf
        EXTENSION=
    - os: linux
      env:
        TARGET=linux-i686
        EXTENSION=

    - os: linux
      env:
        TARGET=windows-x86
        EXTENSION=.exe
      addons:
        apt:
          packages:
            - mingw-w64
    - os: linux
      env:
        TARGET=windows-x64
        EXTENSION=.exe
      addons:
        apt:
          packages:
            - mingw-w64
    - os: osx
      env:
        TARGET=darwin-amd64
        EXTENSION=
  exclude:
    compiler: gcc

addons:
    apt:
      update: true
      packages:
        build-essential
        python-virtualenv
        python3-dev
        python3-pip
        ninja-build
        cmake
        gcc-multilib

before_install:
  # Setup macos build environment
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install meson ninja; fi
  # ensure we do not have curl dev libs, otherwise it caused cross compilations to fail
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y remove libcurl.*-dev; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y remove libpcre*-dev; fi
  # install cross compiler tools if we gonna do binares for arm/raspberry
  # notice it will remove gcc-multilib
  - if [ -z "${TARGET##*arm*}" ]; then sudo apt-get -y install gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf ;fi
  # activate virtualenv with python3, meson requires python3
  - if [ $TRAVIS_OS_NAME = linux ]; then virtualenv .venv --python=python3; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then . .venv/bin/activate; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then pip3 install --upgrade pip; fi
  # install python packages like meson, ninja etc...
  - if [ $TRAVIS_OS_NAME = linux ]; then pip3 install -r requirements.txt; fi
  # add SFTP authentication key to the build environment
  - openssl aes-256-cbc -K $encrypted_1e5406d6c11a_key -iv $encrypted_1e5406d6c11a_iv -in mvdsv_builds.key.enc -out mvdsv_builds.key -d
  # set correct permissions on private key
  - chmod 600 mvdsv_builds.key

# each script section is executed in matrix build
script:
  - mkdir -p build_${TARGET}
  - meson build_${TARGET} --cross-file tools/cross-compilation/${TARGET}.txt
  - ninja -v -C build_${TARGET}
  # print basic info about compiled files
  - file build_${TARGET}/mvdsv${EXTENSION}
  # create hash for download verification
  - md5sum build_${TARGET}/mvdsv${EXTENSION} > build_${TARGET}/mvdsv.md5
    # create built items directories
  - mkdir -p built_assets/{commits,latest}/${TARGET}
  - if [ -n "${TRAVIS_TAG}" ]; then mkdir -p built_assets/stable/${TRAVIS_TAG} ;fi
  - mv build_${TARGET}/mvdsv${EXTENSION} built_assets/commits/${TARGET}/${DATE}_${TRAVIS_COMMIT:0:7}_mvdsv${EXTENSION}
  - mv build_${TARGET}/mvdsv.md5 built_assets/commits/${TARGET}/${DATE}_${TRAVIS_COMMIT:0:7}_mvdsv.md5
  # update stable links if necessary
  - if [ -n "${TRAVIS_TAG}" ]; then cp built_assets/commits/${TARGET}/${DATE}_${TRAVIS_COMMIT:0:7}_mvdsv${EXTENSION} built_assets/stable/${TRAVIS_TAG}/${TARGET}/mvdsv${EXTENSION} ;fi
  - if [ -n "${TRAVIS_TAG}" ]; then cp built_assets/commits/${TARGET}/${DATE}_${TRAVIS_COMMIT:0:7}_mvdsv.md5 built_assets/stable/${TRAVIS_TAG}/${TARGET}/mvdsv.md5 ;fi
  # update latest links
  - cp built_assets/commits/${TARGET}/${DATE}_${TRAVIS_COMMIT:0:7}_mvdsv${EXTENSION} built_assets/latest/${TARGET}/mvdsv${EXTENSION}
  - cp built_assets/commits/${TARGET}/${DATE}_${TRAVIS_COMMIT:0:7}_mvdsv.md5 built_assets/latest/${TARGET}/mvdsv.md5
  # push built items to SFTP storage
  - sftp -q -i mvdsv_builds.key -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${SFTP_PORT} ${SFTP_USERNAME}@${SFTP_HOST}:/ <<< $'put -rp built_assets/*'